name = "vscode-tunnel"
main = "src/index.js"
compatibility_date = "2024-03-12"

[vars]
# These will be populated from .env during deployment
VSCODE_SERVER = ""
AUTH_TOKEN = ""

# Development environment
[env.development]
vars = { }

# Production environment
[env.production]
vars = { }
